command /flameKatana <text>:
	cooldown: 30 seconds
	cooldown message: &4Wait %remaining time% seconds before using this attack again.
	trigger:
		if arg-1 is "34563760386":
			send "slash started"
			set {katanas.player.fireSlash} to true
			wait 10 seconds
			set {katanas.player.fireSlash} to false

on leftclick with iron sword:
	if name of player's held item is "Flame Katana" && {katanas.player.fireSlash} is true:
		drawCircle particle "redstone", center player, id "hihi", rainbowMode true, randomRotation true, radius 1.5, density 20, start 0, visibleRange 30
		
		send "slash"
		send "it works (:Penis in ur mom :) "
on player armor changed:
	if player is wearing iron boots with name "Speed Boots":
		apply swiftness 2 to player for 3000 seconds

	


